package bg.sofia.uni.fmi.mjt.battleships.online.server.command.mode.surfing;

import bg.sofia.uni.fmi.mjt.battleships.online.server.command.response.CommandResponseDTO;
import bg.sofia.uni.fmi.mjt.battleships.online.server.storage.Storage;

import static bg.sofia.uni.fmi.mjt.battleships.online.server.command.manager.CommandExecutor.DEFAULT;
import static bg.sofia.uni.fmi.mjt.battleships.online.server.command.manager.CommandExecutor.RED;

public class Register {
    private static final String ALREADY_LOGGED = "You are already logged in";
    private static final String REGISTER_SUCCESS = "You are now logged in with api-key: %s%s%s";
    private static final int API_KEY_PRIME_RANDOMIZER = 499;

    public static CommandResponseDTO execute(Storage storage, String id) {
        if (storage.getApiKey(id) != null) {
            return new CommandResponseDTO(ALREADY_LOGGED);
        }

        long autoGeneratedApiKey = System.currentTimeMillis() * API_KEY_PRIME_RANDOMIZER;
        String apiKey = Long.toString(autoGeneratedApiKey); // append random chars for more security

        storage.setApiKey(id, apiKey);
        storage.initSavedGamesCollection(apiKey);

        return new CommandResponseDTO(String.format(REGISTER_SUCCESS, RED, apiKey, DEFAULT));
    }
}
